#pragma once

/**
 * This definition contain valid .auth file
 * more: https://github.com/ndunks/WaJs
 */

#define DATA_AUTH_CLIENT_ID "ATTyiDDmnvAS3EJ8ULl+bA=="
#define DATA_AUTH_KEYS_SECRET "LVCE8LsrgypcTAWmZ7ibIxXFuDRpl5YycuIKnBAvvLU="
#define DATA_AUTH_KEYS_PRIVATE "KFCE8LsrgypcTAWmZ7ibIxXFuDRpl5YycuIKnBAvvHU="
#define DATA_AUTH_KEYS_PUBLIC "wgqQStNNKFVoRctkIkYzHsRjjrHlKtZLmONO5EfRc38="
#define DATA_AUTH_SERVER_SECRET "cPpK0lGO2KXhVIXrehgVRmEgBBQjOCeQYW7bWtLze1ySwQXZ3fq0W1Tr4j844Y93B7FAPFf53J3DVJCTuutwPiNxq5g809+iZaWTAzqHIY++6Y2Cr4aBUjijqoFvBB3bWW2cAGwxOVZ0diHcDhRYB7LaKV/VGfr2sZMdWO+5//PW/t8WUDRYyMQS187xKiYU"
#define DATA_AUTH_AESKEY "ro8W8/5p8FTOCwMbLyLUAKIWYBPAn0kmw4GBqM8xOpw="
#define DATA_AUTH_MACKEY "OM3vMoMrU0x5nTDrz8k8ZS8qI9PKewYlaRxf3nUejeA="
#define DATA_AUTH_TOKENS_CLIENT "DBfJ4PCV1kLbQ2up0ZoKFhqKXlHVx/2Zdh6MzfDDVz8FfMIpRmnrodCuAsClz2D2TBktxKLqyWl0rBbJqu7dyQ=="
#define DATA_AUTH_TOKENS_SERVER "1@qKJVYiKP81i8+i8RQaQZaI7MmtMbfCI7mNBSt+vUaQAKZ3cKAekG0rFkr1tfFru1K0xwKUvluUw6MA=="
#define DATA_AUTH_TOKENS_BROWSER "1@4migVn2az+QmVKdiO7LSSfPyPNteqkBtgIgDNwT6tRHuHsEvRcYKwFD+40LxObIprO7j6eMZI1HupxwGFhNuv/DNELIlGVN73gLtZjZ9k77q4zDaQ6k7LK/0yqqLMNEK0vUFaYsYUYhq3v5UJNUQWw=="